server:
  port: 6688


spring:
  application:
    name: springcloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CoderCong/spring-cloud-first.git
#          username:
#          password:

eureka:
  client:
    register-with-eureka: true              #是否将自己注册到Eureka服务中，默认为true
    fetch-registry: true                     #是否从Eureka中获取注册信息，默认为true
    service-url:                              #Eureka客户端与Eureka服务端进行交互的地址
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true          #将自己的ip地址注册到Eureka服务中